[package]
name = "chess"
version = "0.1.0"
authors = ["Brynley Llewellyn-Roux", "Aryan Jassal"]
edition = "2021"
description = "A Rust implementation of the famous game Chess."
repository = "https://github.com/brynblack/chess"
license = "GPL-3.0"

[dependencies]
winit = "0.26.1"
env_logger = "0.9"
log = "0.4.17"
wgpu = "0.12"
pollster = "0.2.5"
