[package]
name = "chess"
version = "0.5.1"
authors = ["Brynley Llewellyn-Roux", "Aryan Jassal"]
edition = "2021"
description = "A Rust implementation of the famous game Chess."
repository = "https://github.com/brynblack/chess"
license = "GPL-3.0"

[dependencies]
bevy = { version = "0.7.0" }
